import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { PROFILE_SERIES, getProfileBySlug } from "@/data/catalog";
import { SITE_NAME, SITE_URL, languageAlternates } from "@/lib/site";
import { localePath } from "@/lib/locale";
import { formatSpecValue, lookup } from "@/lib/specs";
import { LANG_CODES, OG_LOCALES, isLangCode } from "@/i18n/config";
import ru from "@/i18n/locales/ru";
import uz from "@/i18n/locales/uz";
import en from "@/i18n/locales/en";
import { ProfileJsonLd } from "@/components/seo/ProfileJsonLd";
import { ProfileDetailClient } from "./ProfileDetailClient";

/** The branded card generated by app/opengraph-image.tsx. */
const OG_IMAGE = `${SITE_URL}/opengraph-image`;

const LOCALES = { ru, uz, en } as const;
const SEO = { ru: ru.seo, uz: uz.seo, en: en.seo } as const;

/** Pre-render every series in every language (better SEO + speed). */
export function generateStaticParams() {
  return LANG_CODES.flatMap((lang) =>
    PROFILE_SERIES.map((p) => ({ lang, slug: p.slug })),
  );
}

export const dynamicParams = false;

export async function generateMetadata({
  params,
}: {
  params: Promise<{ lang: string; slug: string }>;
}): Promise<Metadata> {
  const { lang, slug } = await params;
  if (!isLangCode(lang)) return {};

  const profile = getProfileBySlug(slug);
  const seo = SEO[lang];

  if (!profile) {
    return { title: seo.title, robots: { index: false } };
  }

  const title = seo.profileTitle.replace("{{name}}", profile.name);

  const depthSpec = profile.specs?.find((s) => s.key === "mountingDepth");
  const depth = depthSpec
    ? formatSpecValue(depthSpec.value, lookup(LOCALES[lang]), lang)
    : undefined;

  const description = seo.profileDescription
    .replace("{{name}}", profile.name)
    .replace(
      "{{category}}",
      profile.category === "facade" ? seo.categoryFacade : seo.categoryPvc,
    )
    .replace(
      "{{depth}}",
      depth ? seo.profileDepth.replace("{{value}}", depth) : "",
    );

  const path = `/profile/${slug}`;

  return {
    title,
    description,
    alternates: {
      canonical: localePath(lang, path),
      languages: languageAlternates(path),
    },
    openGraph: {
      type: "article",
      title: `${title} — ${SITE_NAME}`,
      description,
      url: `${SITE_URL}${localePath(lang, path)}`,
      locale: OG_LOCALES[lang],
      alternateLocale: LANG_CODES.filter((c) => c !== lang).map(
        (c) => OG_LOCALES[c],
      ),
      // Stated outright rather than left to the root opengraph-image file
      // convention, which does not reach this nested route — without it a
      // shared profile link renders as a bare text card.
      images: [{ url: OG_IMAGE, width: 1200, height: 630, alt: SITE_NAME }],
    },
    twitter: {
      card: "summary_large_image",
      title: `${title} — ${SITE_NAME}`,
      description,
      images: [OG_IMAGE],
    },
  };
}

export default async function ProfileDetailPage({
  params,
}: {
  params: Promise<{ lang: string; slug: string }>;
}) {
  const { lang, slug } = await params;
  if (!isLangCode(lang)) notFound();

  const profile = getProfileBySlug(slug);

  return (
    <>
      {profile && <ProfileJsonLd profile={profile} lang={lang} />}
      <ProfileDetailClient slug={slug} />
    </>
  );
}
